### ISSUE TITLE
Estend the documentation for the drone-pipeline setup

### ISSUE THREAD

**Issue by fabiofumarola** [teamdigitale/daf-drone-setup#5]
The actual level of the documentation need to be extended with:
- how to add a pipeline in a project?
- what are the need steps
- explanation and/or link to the official doc where is explained how drone specify pipelines

**Comment by LolloneS** [comment]
new version to be validated: https://github.com/teamdigitale/daf-drone-setup/blob/master/drone-pipeline/README.md
